easy_admin:
    design:
        menu:
            - { entity: 'App\Entity\News' }
            - { dashboard: 'Dashboard', icon: 'fa fa-home', route: 'admin' }
    entities:
        News:
            class: App\Entity\News
            controller_name: App\Controller\Admin\NewsCrudController
            # ...

        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserCrudController
            edit:
        # ...
            fields:
                - email
                - { property: 'avatar', type: 'image' } # Ensure the type is 'image'
                - informations

