security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form-login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin/user/new$, roles: ROLE_ADMIN }
        - { path: ^/admin/user/edit, roles: ROLE_ADMIN }
        - { path: ^/admin/user/delete, roles: ROLE_ADMIN }
        - { path: ^/admin/user, roles: ROLE_ADMIN }
        - { path: ^/admin/user/list, roles: ROLE_MEMBER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        access_control:
            - { path: ^/admin, roles: ROLE_ADMIN}

