controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

admin_dashboard:
    path: /admin
    controller: 'App\Controller\Admin\DashboardController::index'

change_password:
    path: /change-password
    controller: App\Controller\ChangePasswordController::changePassword

admin_news:
    path: /admin/news
    controller: App\Controller\Admin\NewsCrudController::index
    prefix: admin
    name_prefix: admin_
    methods: [GET, POST, PUT, DELETE]

# config/routes.yaml

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout

# not_found:
#     path: /{url}
#     controller: App\Controller\ErrorController::notFound

# config/routes.yaml

contact:
    path: /contact
    controller: App\Controller\ContactController::showContactForm
    methods: ['GET', 'POST']

