# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    server_upload_default_path: '%kernel.project_dir%/public/images'
    server_upload_image_path: '%kernel.project_dir%/public/images'
    avatar_directory: '%kernel.project_dir%/public/images'
    uploads_directory: '%kernel.project_dir%/public/images'
    public_directory: '%kernel.project_dir%/public'

services:
    App\Controller\Admin\DashboardController:
        tags: [ { name: 'controller.service_arguments' }, { name: 'admin' } ]
        public: true
        autowire: true
    
    App\Form\EventType:
        tags: ['form.type']
        
    reservation_email_sender:
        class: App\Service\ReservationEmailSender
        arguments:
            - '@mailer'
            - '@twig' # Use the Twig\Environment service

    App\Controller\Member\MemberEventController:
        public: true

    App\Controller\Admin\NewsCrudController:
        tags: [ { name: 'controller.service_arguments' },  name: 'admin'  ]
        public: true
        autowire: true

    App\Controller\Admin\UserCrudController:
        tags:
            - { name: 'controller.service_arguments' }
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Command\:
        resource: '../src/Command/*'
        tags: ['console.command']
        
    App\Controller\ProfileController:
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'
        tags: ['controller.service_arguments']

    App\EventListener\VisitListener:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    

    App\Controller\Admin\ImagesCrudController:
        tags: [ { name: 'controller.service_arguments' }, { name: 'admin' } ]
        public: true
        autowire: true

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Controller\Admin\:
        resource: '../src/Controller/Admin/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Form\Type\ImageUploadType:
        tags: [form.type]
